mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath*:/mapper/*.xml

spring:
  datasource:
    url: jdbc:mysql://mysql-container:3306/mydatabase
    username: root
    password: my-secret-pw
    driver-class-name: com.mysql.cj.jdbc.Driver
